### ISSUE TITLE
Reorganize WD101 tests repos

### ISSUE THREAD

**Issue by reenas** [pupilfirst/wd101-tests#1]
This repo contains tests for L5, 6 and 7 of WD101. The test and solution for [WD101 capstone](https://github.com/pupilfirst/wd101-capstone-test) are kept separately. 

1. Rename this repo to `wd101-tests` similar to [wd201-tests](https://github.com/pupilfirst/wd201-tests/). 
2. Bring only the tests for WD101 capstone from [wd101-capstone-test](https://github.com/pupilfirst/wd101-capstone-test) in this repo. 
3. Rename [wd101-capstone-test](https://github.com/pupilfirst/wd101-capstone-test) to `wd101-private` and make it private.
4. Add a README file with links to the GitHub actions config for L5, 6, 7 and Capstone on LMS, so it's easy to navigate there.

**Comment by bodhish** [comment]
@reenas It would be great if you could 
1. follow the [ISSUE_TEMPLATE ](https://github.com/pupilfirst/pupilfirst/blob/master/.github/ISSUE_TEMPLATE/feature_request.md) while creating issues. (I have no clue why this has a priority marked as `urgent`; using the template could have helped me understand the context)
2. mark the related changes required for tasks like these; for example, Rename this repo to `wd101-tests` will break all the actions that are referring to this repo;

**Comment by bodhish** [comment]
### Scope 
- [x] Rename [wd101-test-scripts](https://github.com/pupilfirst/wd101-test-scripts) repo to `wd101-tests`
- [x] Fix L5 Github Action in LMS 
- [x] Fix L6 Github Action in LMS
- [x] Fix L7 Github Action in LMS
- [x] Move the capstone test into the repo 
- [x] Fix the capstone test to work with the new setup 
- [x] Update capstone Github Action in LMS
- [x] Test capstone Github Action in LMS
- [x] Rename [wd101-capstone-test](https://github.com/pupilfirst/wd101-capstone-test) to wd101-private


I am ignoring the testing for these actions after the port;

**Comment by harigopal** [comment]
> I am ignoring the testing for these actions after the port

@bodhish I'm reopening this. I'm unsure how this can be closed without testing the changes.

@reenas These changes will probably need to be tested.

**Comment by reenas** [comment]
Thanks @harigopal @bodhish. I have verified that the tests are working okay. Closing this issue.
